version: '2.2'

services:

  nginx:
    build:
      context: ./build/nginx
    container_name: dnmp_nginx
   # depends_on: 
   #   - mysql57
   #   - php72
    ports:
      - "80:80"
      - "443:443"
    networks:
         extnetwork:
    volumes:
      - ./www/php/:/var/www/html/
      - ./www/html/:/var/www/html/html/
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php72:fpm72
     
  php72:
    build:
      context: ./build/php72
    container_name: dnmp_php
    ports:
      - "9000"
    networks:
         extnetwork:
    volumes:
      - ./www/php/:/var/www/html/
      - ./www/html/:/var/www/html/html/
      - ./conf/php72/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php72/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
#      - ./logs/php72/:/var/log/php-fpm/:rw
    links:
     # - "mysql57"
      - "redis"
  
  #mysql57:
    #build:
     #context: ./build/mysql57
    #container_name: dnmp_mysql57
    #ports:
     #- "3306:3306"
    #volumes:
      #- ./data/mysql:/var/lib/mysql
      #- ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      #- ./logs/mysql:/var/log/mysql
    #environment:
      #MYSQL_ROOT_PASSWORD: Root@123
   
  redis:
    build:
      context: ./build/redis
    container_name: dnmp_redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs/redis:/var/log/redis  
    networks:
      extnetwork:
        ipv4_address: 172.19.0.9   
 
networks:
    extnetwork:
       ipam:
         config:
         - subnet: 172.19.0.0/16
           gateway: 172.19.0.1
  #ftp:
    #build:
     #context: ./build/ftp
    #container_name: dnmp_ftp
    #ports:
     #- "20:20"
     #- "21:21"
     #- "21100-21110:21100-21110"
    #volumes:
     #- ./www:/home/vsftpd  
    #environment:
     #- FTP_USER=test
     #- FTP_PASS=test
    
#  composer: 
#    image: composer:1.4.2
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./www:/app:rw
#    working_dir: /app/webroot
#    deploy:
#        restart_policy:
#        condition: none
#    command: composer install
